ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
country=SE

network={
    ssid="Telia-D55420"
    psk=e1b4e5d5b8583a9fbeee02b5a4e37db5e1535da1cf14213119f54f3f67725f23
    key_mgmt=WPA-PSK
}
