#!/bin/sh

case "$1" in
  start)
      modprobe gpioevt gpios=17
    ;;
  stop)
      rmmod gpioevt
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

