#!/bin/sh

case "$1" in
  start)
      start-stop-daemon --start --exec /usr/bin/gpioevtd
    ;;
  stop)
      start-stop-daemon --stop --name gpioevtd
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
